name:                PPQ
version:             0.1.0.0
github:              "githubuser/ppq"
license:             RPL
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ppq#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- s-cargot
- text

library:
  dependencies:
  - base

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

cc-options: -shared

executables:
  PPQ-exe:
    main:                Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wno-missing-export-lists

    dependencies:
    - PPQ

tests:
  PPQ-test:
    main:                Tests.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
