name: Debug

on:
  workflow_dispatch:
    inputs:
      tmate:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - if: matrix.os == 'windows-latest'
        run: |
          choco install html-tidy
          git config --global core.symlinks false

      - name: Configure git
        run: |
          git config --global user.email "ki@example.com"
          git config --global user.name "Ki GithubActions"

      - name: Setup tmate session
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.tmate }}
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
